--
-- PostgreSQL database dump
--

\restrict fd5Upf5LMqUhdPW10ridZgzoHhG872swBLpVXX1YAY3tOuHvzebXVLY3RTcjY6E

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-09-20 23:56:49

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: wasa
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO wasa;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16431)
-- Name: bus; Type: TABLE; Schema: public; Owner: wasa
--

CREATE TABLE public.bus (
    activo boolean,
    fecha_creacion timestamp(6) without time zone,
    id bigint NOT NULL,
    marca_id bigint NOT NULL,
    caracteristicas character varying(255),
    numero_bus character varying(255),
    placa character varying(255)
);


ALTER TABLE public.bus OWNER TO wasa;

--
-- TOC entry 217 (class 1259 OID 16430)
-- Name: bus_id_seq; Type: SEQUENCE; Schema: public; Owner: wasa
--

ALTER TABLE public.bus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16439)
-- Name: marca; Type: TABLE; Schema: public; Owner: wasa
--

CREATE TABLE public.marca (
    id bigint NOT NULL,
    nombre character varying(255)
);


ALTER TABLE public.marca OWNER TO wasa;

--
-- TOC entry 219 (class 1259 OID 16438)
-- Name: marca_id_seq; Type: SEQUENCE; Schema: public; Owner: wasa
--

ALTER TABLE public.marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4798 (class 0 OID 16431)
-- Dependencies: 218
-- Data for Name: bus; Type: TABLE DATA; Schema: public; Owner: wasa
--

COPY public.bus (activo, fecha_creacion, id, marca_id, caracteristicas, numero_bus, placa) FROM stdin;
t	2025-09-20 19:06:35.337657	1	1	Bus de dos pisos con aire acondicionado	BUS-001	ABC-123
t	2025-09-20 19:06:35.337657	2	2	Bus simple con 50 asientos	BUS-002	XYZ-789
\.


--
-- TOC entry 4800 (class 0 OID 16439)
-- Dependencies: 220
-- Data for Name: marca; Type: TABLE DATA; Schema: public; Owner: wasa
--

COPY public.marca (id, nombre) FROM stdin;
1	Volvo
2	Mercedes
3	Scania
\.


--
-- TOC entry 4807 (class 0 OID 0)
-- Dependencies: 217
-- Name: bus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: wasa
--

SELECT pg_catalog.setval('public.bus_id_seq', 2, true);


--
-- TOC entry 4808 (class 0 OID 0)
-- Dependencies: 219
-- Name: marca_id_seq; Type: SEQUENCE SET; Schema: public; Owner: wasa
--

SELECT pg_catalog.setval('public.marca_id_seq', 3, true);


--
-- TOC entry 4648 (class 2606 OID 16437)
-- Name: bus bus_pkey; Type: CONSTRAINT; Schema: public; Owner: wasa
--

ALTER TABLE ONLY public.bus
    ADD CONSTRAINT bus_pkey PRIMARY KEY (id);


--
-- TOC entry 4650 (class 2606 OID 16443)
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: public; Owner: wasa
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY (id);


--
-- TOC entry 4651 (class 2606 OID 16444)
-- Name: bus fk6mmbt43kmdip2jh71qpynr0xl; Type: FK CONSTRAINT; Schema: public; Owner: wasa
--

ALTER TABLE ONLY public.bus
    ADD CONSTRAINT fk6mmbt43kmdip2jh71qpynr0xl FOREIGN KEY (marca_id) REFERENCES public.marca(id);


--
-- TOC entry 4806 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: wasa
--

REVOKE ALL ON SCHEMA public FROM wasa;
GRANT ALL ON SCHEMA public TO wasa WITH GRANT OPTION;


--
-- TOC entry 2049 (class 826 OID 16410)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO wasa WITH GRANT OPTION;


-- Completed on 2025-09-20 23:56:49

--
-- PostgreSQL database dump complete
--

\unrestrict fd5Upf5LMqUhdPW10ridZgzoHhG872swBLpVXX1YAY3tOuHvzebXVLY3RTcjY6E

