--
-- PostgreSQL database dump
--

\restrict 3nYMlEWcc6l3bdgAZqCuMclEjCvYTCnl7Nw5cu78dJMSaU7gFz6SfNwOplEcFh1

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-09-21 00:25:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: wasa
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO wasa;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16431)
-- Name: bus; Type: TABLE; Schema: public; Owner: wasa
--

CREATE TABLE public.bus (
    activo boolean,
    fecha_creacion timestamp(6) without time zone,
    id bigint NOT NULL,
    marca_id bigint NOT NULL,
    caracteristicas character varying(255),
    numero_bus character varying(255),
    placa character varying(255)
);


ALTER TABLE public.bus OWNER TO wasa;

--
-- TOC entry 217 (class 1259 OID 16430)
-- Name: bus_id_seq; Type: SEQUENCE; Schema: public; Owner: wasa
--

ALTER TABLE public.bus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16439)
-- Name: marca; Type: TABLE; Schema: public; Owner: wasa
--

CREATE TABLE public.marca (
    id bigint NOT NULL,
    nombre character varying(255)
);


ALTER TABLE public.marca OWNER TO wasa;

--
-- TOC entry 219 (class 1259 OID 16438)
-- Name: marca_id_seq; Type: SEQUENCE; Schema: public; Owner: wasa
--

ALTER TABLE public.marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4798 (class 0 OID 16431)
-- Dependencies: 218
-- Data for Name: bus; Type: TABLE DATA; Schema: public; Owner: wasa
--

COPY public.bus (activo, fecha_creacion, id, marca_id, caracteristicas, numero_bus, placa) FROM stdin;
t	2025-09-20 19:06:35.337657	1	1	Bus de dos pisos con aire acondicionado	BUS-001	ABC-123
t	2025-09-20 19:06:35.337657	2	2	Bus simple con 50 asientos	BUS-002	XYZ-789
t	2025-09-21 00:07:36.256504	3	3	Aire acondicionado	BUS-003	GHI-303
t	2025-09-21 00:07:36.256504	4	4	WiFi, TV	BUS-004	JKL-404
t	2025-09-21 00:07:36.256504	5	5	Asientos reclinables, WiFi	BUS-005	MNO-505
t	2025-09-21 00:07:36.256504	6	6	Aire acondicionado, TV	BUS-006	PQR-606
t	2025-09-21 00:07:36.256504	7	7	WiFi	BUS-007	STU-707
t	2025-09-21 00:07:36.256504	8	8	Aire acondicionado, Asientos reclinables	BUS-008	VWX-808
t	2025-09-21 00:07:36.256504	9	9	TV	BUS-009	YZA-909
t	2025-09-21 00:07:36.256504	10	10	WiFi, Aire acondicionado	BUS-010	BCD-010
t	2025-09-21 00:07:36.256504	11	11	Asientos reclinables	BUS-011	EFG-111
t	2025-09-21 00:07:36.256504	12	12	TV, WiFi	BUS-012	HIJ-212
t	2025-09-21 00:07:36.256504	13	13	Aire acondicionado	BUS-013	KLM-313
t	2025-09-21 00:07:36.256504	14	14	Asientos reclinables, TV	BUS-014	NOP-414
t	2025-09-21 00:07:36.256504	15	15	WiFi	BUS-015	QRS-515
t	2025-09-21 00:07:36.256504	16	16	Aire acondicionado, WiFi	BUS-016	TUV-616
t	2025-09-21 00:07:36.256504	17	17	TV	BUS-017	WXY-717
t	2025-09-21 00:07:36.256504	18	18	Asientos reclinables, WiFi	BUS-018	ZAB-818
t	2025-09-21 00:07:36.256504	19	19	Aire acondicionado	BUS-019	CDE-919
t	2025-09-21 00:07:36.256504	20	20	WiFi, TV	BUS-020	FGH-020
\.


--
-- TOC entry 4800 (class 0 OID 16439)
-- Dependencies: 220
-- Data for Name: marca; Type: TABLE DATA; Schema: public; Owner: wasa
--

COPY public.marca (id, nombre) FROM stdin;
1	Volvo
2	Mercedes
3	Scania
4	Fiat
5	Mercedes
6	Toyota
7	Renault
8	Iveco
9	Mitsubishi
10	Hyundai
11	Ford
12	Hino
13	Isuzu
14	Tata
15	Kamaz
16	Foton
17	King Long
18	BYD
19	Yutong
20	Ashok Leyland
\.


--
-- TOC entry 4807 (class 0 OID 0)
-- Dependencies: 217
-- Name: bus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: wasa
--

SELECT pg_catalog.setval('public.bus_id_seq', 20, true);


--
-- TOC entry 4808 (class 0 OID 0)
-- Dependencies: 219
-- Name: marca_id_seq; Type: SEQUENCE SET; Schema: public; Owner: wasa
--

SELECT pg_catalog.setval('public.marca_id_seq', 3, true);


--
-- TOC entry 4648 (class 2606 OID 16437)
-- Name: bus bus_pkey; Type: CONSTRAINT; Schema: public; Owner: wasa
--

ALTER TABLE ONLY public.bus
    ADD CONSTRAINT bus_pkey PRIMARY KEY (id);


--
-- TOC entry 4650 (class 2606 OID 16443)
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: public; Owner: wasa
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY (id);


--
-- TOC entry 4651 (class 2606 OID 16444)
-- Name: bus fk6mmbt43kmdip2jh71qpynr0xl; Type: FK CONSTRAINT; Schema: public; Owner: wasa
--

ALTER TABLE ONLY public.bus
    ADD CONSTRAINT fk6mmbt43kmdip2jh71qpynr0xl FOREIGN KEY (marca_id) REFERENCES public.marca(id);


--
-- TOC entry 4806 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: wasa
--

REVOKE ALL ON SCHEMA public FROM wasa;
GRANT ALL ON SCHEMA public TO wasa WITH GRANT OPTION;


--
-- TOC entry 2049 (class 826 OID 16410)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO wasa WITH GRANT OPTION;


-- Completed on 2025-09-21 00:25:46

--
-- PostgreSQL database dump complete
--

\unrestrict 3nYMlEWcc6l3bdgAZqCuMclEjCvYTCnl7Nw5cu78dJMSaU7gFz6SfNwOplEcFh1

